### ISSUE TITLE
Expected date for releasing the code

### ISSUE THREAD

**Issue by carlosedubarreto** [yohanshin/WHAM#1]
the project looks amazing.
Whet is the expected date for releasing the code?

**Comment by yohanshin** [comment]
Hi! I appreciate your interest. We plan to release the trained models and evaluation scripts next week and the entire training code after the holidays. Please stay tuned for future updates!

**Comment by nguyenquivinhquang** [comment]
Thank you for invaluable method. Could you also share the implementation of the PACE code?

**Comment by yohanshin** [comment]
Hi @nguyenquivinhquang , we do not have PACE implementation, and thus, we only include PACE's official results on our table. Also, the PACE's runtime graph in our supplementary video is not official, it is estimated using SLAHMR's speed. I hope this answers your question, thanks!

**Comment by HonglinChu** [comment]
> Hi! I appreciate your interest. We plan to release the trained models and evaluation scripts next week and the entire training code after the holidays. Please stay tuned for future updates!

Great work, the trained models will be released this week,really?

**Comment by carlosedubarreto** [comment]
looks like it was released, closing the issue, thanks
