### ISSUE TITLE
Questions on SMPL Rendering in Video Demo and Initialization of Trajectory Decoder

### ISSUE THREAD

**Issue by zehongs** [yohanshin/WHAM#10]
Hello, thanks for the great work! I am currently trying to understand your paper and have a couple of questions:
1. SMPL Rendering in Video Demo: In the video demonstration where SMPL is rendered onto the observed image, are the root-global-orientation and camera-parameters predicted by the motion-decoder being used? Also, is it feasible to substitute these with the global-orientation provided by the trajectory-refiner? If so, how might this change affect the results?
2. Trajectory Decoder Initialization: Regarding the initialization of the trajectory decoder, are there specific requirements for the input root pose (6d)? For instance, does it need to align with the direction of gravity?

**Comment by yohanshin** [comment]
Hi @zehongs , thank you for your interest in our work! 

1. Camera-coordinate SMPL rendering does not require global root orientation. Instead, our Motion Decoder directly estimates weak-perspective camera translation and camera-coordinate root orientation, and we use this to render SMPL meshes. When I visualize the world-grounded motion (I used aitviewer in the meantime), we use root-global-orientation given from the Refiner module. So the current version of WHAM estimates three different global orientations, one is in a camera coordinate system (Motion Decoder), and the other two are in the global coordinate system (Trajectory Decoder and Refiner). Currently, camera-coordinate orientation is independent of the global-coordinate orientations, so even though we update root orientation through the refining module, this does not affect the rendering onto the input video sequence.

2. This is a great question! As our decoder systems estimate the current state recursively, we need values at time `t` to estimate the values at time `t+1`. Hence, it is ideal to have the root orientation (or yaw and pitch angles of the camera) at time `t=0` to get better trajectory decoding. This can be integrated with some previous work such as [SPEC](https://github.com/mkocabas/SPEC) or [W-HMR](https://github.com/yw0208/W-HMR). Or you can naively set the camera pose at the time `t=0` is an identical 3x3 matrix -- this will give you incorrect root orientation at the beginning but WHAM will then smoothly refine the orientation to match with the global coordinate accordingly.

**Comment by yohanshin** [comment]
Just updated `lib/eval/evaluate_3dpw.py` script so that you can render the prediction onto the input video. Once you download 3DPW data and store at `dataset/3DPW`, you can run:

```bash
python -m lib.eval.evaluate_3dpw --render True --cfg configs/yamls/demo.yaml TRAIN.CHECKPOINT checkpoints/wham_vit_w_3dpw.pth.tar
```

to create a rendered video with the prediction. Let me know if this script does not work in your environment. It requires PyTorch3D.

**Comment by zehongs** [comment]
Thank you for your comprehensive reply, which has significantly enhanced my understanding of WHAM. The project is really cool. 

I've managed to get the rendered SMPL on 3DPW image sequences like this:
![image](https://github.com/yohanshin/WHAM/assets/25296730/dc8fb86c-efc1-46de-b64b-5eef7a9fdb52)

By the way, I think this line works better:
`pip install https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1110/pytorch3d-0.7.2-cp39-cp39-linux_x86_64.whl`
There was an `ERROR: No matching distribution found for pytorch3d`.

**Comment by yohanshin** [comment]
Hi @zehongs , thank you for your notes! I realize that I made a mistake in the PyTorch versioning for installing PyTorch3D. Yes, I just checked and pyt1110 is the correct version for this environment. I will update this soon, and I am glad that it worked at your end :)
