### ISSUE TITLE
Export/Import to 3D software

### ISSUE THREAD

**Issue by Inferencer** [yohanshin/WHAM#19]
I noticed in a closed comment about the output stating that

> The future demo code with custom videos will support visualization and storing SMPL parameters.

Would it be possible for either yourself (owner) or another member of the opensource community to write a guide on importing the resulting data to visualize as a 3D model in Blender?

I'm just starting to research this field so I apologize if that is a simple or complicated task.

Best regards

**Comment by carlosedubarreto** [comment]
With the help of this code and having the SMPL parameters is possible to load the data in blender (that is what I do ☺️)

https://github.com/mkocabas/VIBE/blob/master/lib/utils/fbx_output.py
