### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by linjiangya** [yohanshin/WHAM#21]
Dear authors,

Thank you for this amazing work!  May I know if you have a plan to release the code for training?

**Comment by yohanshin** [comment]
Hi @linjiangya , yes -- we are planning to release our training code. Currently we are almost there to release the demo run and the next step should be the training framework. Thanks for asking!

**Comment by linjiangya** [comment]
> Hi @linjiangya , yes -- we are planning to release our training code. Currently we are almost there to release the demo run and the next step should be the training framework. Thanks for asking!

Thank you for your prompt reply! Looking forward to it. By the way, is there an approximate date for the training code?

**Comment by yohanshin** [comment]
Hi @linjiangya , I will try my best to release a tentative training code during the 4th week of January. This can be delayed to early February though :(. Before then, I am always happy to answer any question related to the training and implementation, please [email me](mailto:soyongs@andrew.cmu.edu) for details.

**Comment by linjiangya** [comment]
> Hi @linjiangya , I will try my best to release a tentative training code during the 4th week of January. This can be delayed to early February though :(. Before then, I am always happy to answer any question related to the training and implementation, please [email me](mailto:soyongs@andrew.cmu.edu) for details.

Great! Thank you for your reply :) I'll close this for now.
