### ISSUE TITLE
huh? 2d keypoints? vit? is this a fake github repo? 

### ISSUE THREAD

**Issue by jez-moxmo** [yohanshin/WHAM#22]

**Comment by yohanshin** [comment]
Hi @jez-moxmo , can you please specify your question? I don't get the correlation between keypoints, ViT, and a fake repo. Let me know if we are missing an important thing in our work, I would sincerely appreciate your feedback. Thanks!

**Comment by RohaanA** [comment]
> Hi @jez-moxmo , can you please specify your question? I don't get the correlation between keypoints, ViT, and a fake repo. Let me know if we are missing an important thing in our work, I would sincerely appreciate your feedback. Thanks!

Hey, this is off topic but if you don't mind can you tell me an expected release date for the code for in the wild videos? I'd really like to see this model's performance in Tennis matches.

**Comment by yohanshin** [comment]
Hi @RohaanA , we will release the demo code by this week but maybe not with Colab. Sorry for the delayed release, just need some more time to documenting the instructions and cleaning the code (+ and small troubleshooting happening during the cleaning).

**Comment by yohanshin** [comment]
Close this post as the user did not specify the issue to tackle.
