### ISSUE TITLE
How to download the dpvo.pth?

### ISSUE THREAD

**Issue by WenjiaWang0312** [yohanshin/WHAM#24]
Dear author, thanks for your sharing. But I cannot find the dpvo.pth file, which is required to run the demo.py

**Comment by yohanshin** [comment]
Hi @WenjiaWang0312
Sorry for the confusion. I realized that I missed one line of the code in `fetch_demo_data.sh` file to download dpvo checkpoint. Please run the following line:

```bash
gdown "https://drive.google.com/uc?id=1kXTV4EYb-BI3H7J-bkR3Bc4gT9zfnHGT&export=download&confirm=t" -O 'checkpoints/dpvo.pth'
```

This will download DPVO model that is provided by the official repo [here](https://github.com/princeton-vl/DPVO/blob/main/download_models_and_data.sh).

I will update the script shortly. Please let me know if there is any issue other than this occurring. Thanks for the heads up!

**Comment by RohaanA** [comment]
Hi,

I was trying out the demo script on google colab. Upon running the script and also downloading the dvpo model, I run into this error when running the demo script.

<img width="960" alt="image" src="https://github.com/yohanshin/WHAM/assets/75722072/f1912130-f2cf-4a5f-9043-95364a66d0a5">

**Comment by yohanshin** [comment]
Hi @RohaanA 

-lI think you are getting this error message since you have not properly installed DPVO. Have you followed the installation instruction? I also updated the installation, please refer to this document [here](https://github.com/yohanshin/WHAM/blob/main/docs/INSTALL.md) and follow the instruction. 

Please let me know if you are having any other issue after the installation.

**Comment by RohaanA** [comment]
> Hi @RohaanA
> 
> -lI think you are getting this error message since you have not properly installed DPVO. Have you followed the installation instruction? I also updated the installation, please refer to this document [here](https://github.com/yohanshin/WHAM/blob/main/docs/INSTALL.md) and follow the instruction.
> 
> Please let me know if you are having any other issue after the installation.

Oh you're right, I missed this page! Thank you I'll try it now
