### ISSUE TITLE
checkerboard minimum size

### ISSUE THREAD

**Issue by WenjiaWang0312** [yohanshin/WHAM#29]
Dear author, the checkerboard size would be 0 if the person moves slightly in the video. https://github.com/yohanshin/WHAM/blob/main/lib/vis/tools.py#L174C51-L174C51
So I recommend setting a minimum row and col number: `num_rows = num_cols = max(2, int(length / tile_width))`

**Comment by yohanshin** [comment]
Hi @WenjiaWang0312 

Thank you so much for pointing this out. I haven't thought about the edge cases during the visualization, and yes, I will make those changes. I appreciate your feedback!
