### ISSUE TITLE
When running the demo, the program gets stuck

### ISSUE THREAD

**Issue by ninefivefly** [yohanshin/WHAM#32]
Dear authors,

Thank you for this amazing work! 

After I installed it successfully, when I ran the demo, the program got stuck in the transform function in projective_ops.py in the dpvo module.

![image](https://github.com/yohanshin/WHAM/assets/9336282/d8488f2f-7ce1-46ed-acb4-9b100879c8ee)
![image](https://github.com/yohanshin/WHAM/assets/9336282/3c62390b-2197-47b8-b9c4-4483a4075721)

 Anyone else having this problem or have an idea where to start in solving it?

**Comment by yohanshin** [comment]
Hi @ninefivefly ,

thank you for your interest in our work! I haven't had any issues related to yours, so I think this needs to be debugged further. When you say the program got stuck, do you mean it keeps running (no exiting with error message)? Would you take a look at [DPVO's official repo](https://github.com/princeton-vl/DPVO/tree/main) and see if anyone else posts similar issues as yours?

**Comment by ninefivefly** [comment]
@yohanshin   Thank you very much. I found out that it is because when using cuda to perform inverse() operation, it will get stuck. From the task manager, I can see that the program has been suspended. I just switched to cpu and it was fine.
