### ISSUE TITLE
The order of regressed keypoints?

### ISSUE THREAD

**Issue by xjwxjw** [yohanshin/WHAM#33]
Hi, I would like to ask, what's the order of keypoints regressed from J_regressor_wham?

**Comment by yohanshin** [comment]
Hi @xjwxjw 

It is 31 keypoints where the first 17 keypoints follow the COCO configuration and the subsequent 14 keypoints follow the "common J14" configuration. You can find the detailed order of joints of those configurations [VIBE code](https://github.com/mkocabas/VIBE/blob/master/lib/data_utils/kp_utils.py) (check `get_coco_joint_names` and `get_common_joint_names`).
