### ISSUE TITLE
Inquiry Regarding Model Output

### ISSUE THREAD

**Issue by lalasray** [yohanshin/WHAM#38]
Dear authors,

Thank you for the amazing paper. I have a question regarding output If i want to extract the 3D pose from your model is it **pred["pose"]** or **pred["poses_body"]**  and can you please tell me the difference between both.

**Comment by yohanshin** [comment]
Hi @lalasray ,

Thank you for your interest in our work! `pred["pose"]` is a whole-body pose in 6D rotation representation, which will be used during the training. So you can use `pred["poses_body"]` if you want the complete 3D rotation. This will have the shape of `(batch_size * num_frames, 23, 3, 3)` where 23 stands for 23 body joints in SMPL (0th index - left hip, 1st index - right hip, and so on). If you want the global orientation of the person, `pred["poses_root_cam"]` is the global orientation of the person wrt the camera, where `pred["poses_root_world"]` is the one wrt the global coordinate.

**Comment by lalasray** [comment]
Thank you @yohanshin

**Comment by GuoPingPan** [comment]
@yohanshin Hi, such a great job. 
I want to get all the 23 joints rotation in camera frame and I had tried to use `pred["poses_body"]` as relative rotation to "pred['poses_root_cam']".
But the result is that the "pred['poses_root_cam']" can be showed correctly by using `cv2.drawFrameAxes` while the shoulders can't.
my code
```
    spine1 = rotation_matrixs[2]
    spine2 = rotation_matrixs[5]
    spine3 = rotation_matrixs[8]

    connect_middle = np.dot(spine3, np.dot(spine2, np.dot(spine1, root_rot_cam)))
    left_shoulder_rotation = rotation_matrixs[12]
    right_shoulder_rotation = rotation_matrixs[13]
    
    left_shoulder_cam = np.dot(left_shoulder_rotation, connect_middle)
    right_shoulder_cam = np.dot(right_shoulder_rotation, connect_middle)
```
