### ISSUE TITLE
Import PKL to Blender

### ISSUE THREAD

**Issue by carlosedubarreto** [yohanshin/WHAM#52]
I saw that there was another issue with the tip to get the code from VIBE, I did some rewrite to that code and put in a blend file to be easier to use.

Just need to install joblib in blender (there is a tab with the installation script) and add the SMPL fbx for male on the same folder as you have the blend file, and put the path to the pkl file.

Hope its useful
[loading_WHAM_import_SMPL_FINAL.zip](https://github.com/yohanshin/WHAM/files/14146057/loading_WHAM_import_SMPL_FINAL.zip)

**Comment by carlosedubarreto** [comment]
I made a video showing the process on google colab and on how to use the blend file.

you can see it in youtube : https://youtu.be/7heJSFGzxAI

or on my patreon site: https://www.patreon.com/posts/wham-in-google-97760199?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link

If you have problems understanding what I'm saying, there is closed caption available.

**Comment by mrEuler** [comment]
@carlosedubarreto you are fast man! BTW your 4d humans plugin helped a lot, but would be cool, if your plugins would support linux systems :)

**Comment by carlosedubarreto** [comment]
@mrEuler 
LOL. Took me more than a week to make it work, I consider that slow 😁
and was able to make it work only because  2 other people helped me.

Oh, about linux, that is complicated, since I do a workaround to make the process use a different python than the blender one, this way I'm sure it wont cause problems to blender versions and the heavy data that is installed is interchangeable iwth other versions of blender inside the user pc.

I could probably do some code for it to work on linux, but, to be honest I hardly have time to code for windows, that is my main system.

To be able to make for linux I would need to work full time on this, something I cannot do or else I'll starve 😅.

So I'm not saying that wont be linux versions, but it will be much more difficult for me to make them.

And thanks for the words 😍

**Comment by mrEuler** [comment]
@carlosedubarreto No worries, actually I was able to put everything from your plugin and blender inside the docker container and make it working almost everywhere, where CUDA is correct.

**Comment by carlosedubarreto** [comment]
Just the script for the ones that dont have blender
[import_WHAM_in blender.txt](https://github.com/yohanshin/WHAM/files/14828696/import_WHAM_in.blender.txt)

**Comment by iamthephd** [comment]
@carlosedubarreto 
Nice work for the blender script! Do you know how to apply the animation i.e. output from WHAM to Mixamo rig? I tried using changing the bone names, but the animation look weird...

**Comment by hynynghan** [comment]
@carlosedubarreto Thank you for your effort!
Based on your excellent contribution, I have further worked on the code to convert it into an FBX file format that can be imported into Unity. With this code, you no longer need to manually change the vertical axis in Blender.

[pkl2fbx4unity.txt](https://github.com/user-attachments/files/16728514/pkl2fbx4unity.txt)

**Comment by g8392** [comment]
> Just the script for the ones that dont have blender [import_WHAM_in blender.txt](https://github.com/yohanshin/WHAM/files/14828696/import_WHAM_in.blender.txt)

Thanks everyone for the effort, I'm trying the scripts but either the original one or the ones you shared here give me this  KeyError: 'pose' or if I change the character number sometimes gets to:

```  File "/media/ed/FSSD/DATA/GITHUB/VIBE/demo2.py", line 138, in <module>
    apply_trans_pose_shape(Vector(tran), pose_final, shape, obj,arm_ob, obname, scene, cam_ob, fframe)
  File "/media/ed/FSSD/DATA/GITHUB/VIBE/demo2.py", line 68, in apply_trans_pose_shape
    mrots, bsh = rodrigues2bshapes(pose)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ed/FSSD/DATA/GITHUB/VIBE/demo2.py", line 59, in rodrigues2bshapes
    mat_rots = [Rodrigues(rod_rot) for rod_rot in rod_rots]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ed/FSSD/DATA/GITHUB/VIBE/demo2.py", line 59, in <listcomp>
    mat_rots = [Rodrigues(rod_rot) for rod_rot in rod_rots]
                ^^^^^^^^^^^^^^^^^^
  File "/media/ed/FSSD/DATA/GITHUB/VIBE/demo2.py", line 44, in Rodrigues
    mat = np.asarray([[0, -r[2], r[1]],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.
```

I've got WHAM working on different videos but can't seem to get the data out. 

____

I've got it working by using a 2.83 blender and numpy 1.21.1, anyone has also extracted the camera pose?

**Comment by hynynghan** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-09-26T02:09:29
          
          
            * 메일 제목 : 
Re: [yohanshin/WHAM] Import PKL to Blender (Issue #52)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by baesky** [comment]
great work!
I use it in blender 4.4 and got some err:
Python: Traceback (most recent call last):
```
  File "F:\loading_WHAM_import_SMPL_FINAL.blend\FINAL_Script", line 113, in <module>
  File "F:\loading_WHAM_import_SMPL_FINAL.blend\FINAL_Script", line 93, in init_scene
KeyError: 'bpy_prop_collection[key]: key "m_avg" not found'
```
@carlosedubarreto

**Comment by hynynghan** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2025-06-23T14:02:39
          
          
            * 메일 제목 : 
Re: [yohanshin/WHAM] Import PKL to Blender (Issue #52)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by kihot** [comment]
I have written a script based on your script that allows you to generate an FBX file from a video with a single command. To do this, you first need to download the basicModel_m_lbs_10_207_0_v1.02.fbx file. I tested the script using WSL. 
You will need to place both the scripts and the FBX file in the root folder of WHAM, then run "python run_wham.py --video examples/IMG_9730.mov". The generated FBX file will be placed in the output folder after the command has finished running.
Maybe it will be useful to someone.
[blender_export_worker.py](https://github.com/user-attachments/files/25422767/blender_export_worker.py)
[run_wham.py](https://github.com/user-attachments/files/25422766/run_wham.py)

**Comment by hynynghan** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2026-02-20T02:20:33
          
          
            * 메일 제목 : 
Re: [yohanshin/WHAM] Import PKL to Blender (Issue #52)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 현재 메일 수신을 제한하고 있습니다.
이 설정은 개인 또는 조직의 메일 수신 정책에 의해 적용되었습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by carlosedubarreto** [comment]
> [@carlosedubarreto](https://github.com/carlosedubarreto) Nice work for the blender script! Do you know how to apply the animation i.e. output from WHAM to Mixamo rig? I tried using changing the bone names, but the animation look weird...

@iamthephd 
Oh mn sorry, I didnt see your question before, in case you didnt find, you need to do something called retarget to take an animation from one to send to another rig.

**Comment by hynynghan** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2026-06-16T17:03:38
          
          
            * 메일 제목 : 
Re: [yohanshin/WHAM] Import PKL to Blender (Issue #52)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 현재 메일 수신을 제한하고 있습니다.
이 설정은 개인 또는 조직의 메일 수신 정책에 의해 적용되었습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by carlosedubarreto** [comment]
> great work! I use it in blender 4.4 and got some err: Python: Traceback (most recent call last):
> 
> ```
>   File "F:\loading_WHAM_import_SMPL_FINAL.blend\FINAL_Script", line 113, in <module>
>   File "F:\loading_WHAM_import_SMPL_FINAL.blend\FINAL_Script", line 93, in init_scene
> KeyError: 'bpy_prop_collection[key]: key "m_avg" not found'
> ```
> 
> [@carlosedubarreto](https://github.com/carlosedubarreto)

@baesky , probably you got a different fbx file.
since the code searched to the parameters that are inside the male FBX file.
the "m_avg" I think its the name of the armature when you load the fbx of the male in blender

**Comment by hynynghan** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2026-06-16T17:06:22
          
          
            * 메일 제목 : 
Re: [yohanshin/WHAM] Import PKL to Blender (Issue #52)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 현재 메일 수신을 제한하고 있습니다.
이 설정은 개인 또는 조직의 메일 수신 정책에 의해 적용되었습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
