### ISSUE TITLE
Installing WHAM on windows

### ISSUE THREAD

**Issue by carlosedubarreto** [yohanshin/WHAM#53]
I was trying since last week to install on windows but I was having problems with DPVO and lietorch.

agreat guy called @psiydown helped a lot and another person from the lietorch github.

I created this issue so it could be easier to people to find how to process that part.

I'll add here the notes I used as reference and the files that I had to change to compile DPVO.

**Comment by carlosedubarreto** [comment]
# Clone the repo
```
git clone https://github.com/yohanshin/WHAM.git --recursive
```

```
cd DPVO/
```

# Create Conda environment
```
conda create -n wham python=3.9
```
```
conda activate wham
```

##if you already have cuda 11.3 and its not the latest one installed youll have to execute something like this
```bash
set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
```

# Install PyTorch libraries

```
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
```

# Install PyTorch3D (optional) for visualization 


Instalacao seguindo instrucoes de [[Pytorch3d instrucoes de intalacao pytorch3d no windows]]
```bash
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
```

this part you need to have visual studio installed or vs build tools with C++
```bash
%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
```

```bash
git clone https://github.com/facebookresearch/pytorch3d.git
```

```bash
cd pytorch3d
set DISTUTILS_USE_SDK=1
python setup.py install
```

```
cd ..
```


# Install WHAM dependencies
```bash
pip install -r requirements.txt
```

# Install ViTPose
```bash
pip install -v -e third-party/ViTPose
```

# Install DPVO

```bash
cd third-party/DPVO
```

**save the eigen in the  thirdparty folder**
the full path would be  this:
D:\AI\0_mocap\WHAM\WHAM\third-party\DPVO\thirdparty\eigen-3.4.0


```bash
conda install pytorch-scatter=2.0.9 -c rusty1s
```

if you didnt run this command before, you'll have to run it to be able to compile DPVO
```
%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
set DISTUTILS_USE_SDK=1
```


```
pip install .
```


BUTTTTTTTTT

before compiling DPVO youll need to change some files
the files you need to change are
`correlation_kernel.cu`
`ba.cpp`
`ba_cuda.cu`

 `lietorch_gpu.cu`

Ihere are the files already changed and that worked for me.

path: D:\AI\0_mocap\WHAM\WHAM\third-party\DPVO\dpvo\altcorr
[correlation_kernel.zip](https://github.com/yohanshin/WHAM/files/14146118/correlation_kernel.zip)


path D:\AI\0_mocap\WHAM\WHAM\third-party\DPVO\dpvo\fastba
[fastba.zip](https://github.com/yohanshin/WHAM/files/14146120/fastba.zip)


path: D:\AI\0_mocap\WHAM\WHAM\third-party\DPVO\dpvo\lietorch\src
[lietorch_gpu.zip](https://github.com/yohanshin/WHAM/files/14146123/lietorch_gpu.zip)


and to run exporting the pkl you'll have to use

`python demo.py --video examples/IMG_9732.mov --visualize --save_pkl`

I think that if you want to use it in blender, you wont need the video generated, probably you wont need to install pytorch3d. I didnt test it.

so maybe if you want to try, you could skip installing pytorch3d and use the following command

`python demo.py --video examples/IMG_9732.mov --save_pkl`

I hope its useful for everyone. It took me a long time t make it work here and I hope more people dont have to suffer that much too 😀

And greeting to the author, its an amazing project 👏🦾🎉

**Comment by fandy422** [comment]
Thx,it's useful for me.Cool!
