### ISSUE TITLE
Can it running in realtime?

### ISSUE THREAD

**Issue by yuhuison** [yohanshin/WHAM#6]
作者您好，我想问问这种方法是不是有机会做到实时输入视频流进行动捕呢，把RNN的状态暂存到下一帧做init的话🤔

**Comment by yohanshin** [comment]
Sorry, I am not Chinese and thus, I don't understand the question...

You may be asking about the capability for real-time inference. Our core system, excluding bbox detection, person identification, keypoints detection, and SLAM runs at nearly 200 fps, but we currently do not have such an implementation in real-time. I believe, as there are many real-time solutions for 2D detections and SLAM, real-time inference should be feasible if you package things up nicely :)

**Comment by zehongs** [comment]
Hi, what do you think about image feature extraction? I believe it takes a lot of time.

**Comment by yohanshin** [comment]
Hi @zehongs , yes -- feature extraction takes longer time than RNN modules. However, from our previous runtime experiments, image feature extraction was not a bottleneck. If we run in a batch mode, feature extraction itself runs in ~240 fps. Please refer to our supplementary document for details.

**Comment by imabackstabber** [comment]
Hi, just new to this area and not familiar with SLAM, I wonder whether you can provide inference speed about SLAM and I'll be very thankful :) @yohanshin

**Comment by yohanshin** [comment]
Hi @imabackstabber , it depends on what SLAM algorithm you are using, but from DPVO's original paper [link](https://arxiv.org/pdf/2208.04726.pdf), DPVO runs at around 120 fps. Hope this answers your question!
