### ISSUE TITLE
'Auxiliary SMPL-related data' url may broken

### ISSUE THREAD

**Issue by chojinie** [yohanshin/WHAM#60]
Thank you for share nice work!

I tried to google colab the day before yesterday. And it worked nicely.

But, I try to installation on local today. There are some problem.

On data preparation process, in fetch_demo_data.sh file,

# Auxiliary SMPL-related data
wget "https://drive.google.com/uc?id=1pbmzRbWGgae6noDIyQOnohzaVnX_csUZ&export=download&confirm=t" -O 'dataset/body_models.tar.gz'
tar -xvf dataset/body_models.tar.gz -C dataset/

When i tried to activate getting data command, i got this message.

![image](https://github.com/yohanshin/WHAM/assets/106041887/432a1f16-14ff-4171-9eb7-ed062f244113)

**Comment by carlosedubarreto** [comment]
Hello @chojinie .

From that message seems the automation for the body_models data is not working, but it also says that you can fet it manually on the browser.

I k ow its not the best option, but if you look on the script that dowbloads that file, it does something simple.

It dowbloads the file and extract it.

If you can dowbload it,  you could extract to the location that the script says.

I could send you the file, but i can turn on my pc now (some problems with the eletricity provider im waiting for them to fix)

Hope it works for you.

**Comment by RohaanA** [comment]
> Thanks @carlosedubarreto for your explanation!
> 
> Hi @chojinie , I also recognized this issue yesterday and trying to find a way to resolve it --previously, I had a similar issue which was resolved by downgrading `gdown` to version `4.6.0`, but apparently, this version is not working again. Once we fix this, we will update `fetch_demo_data.sh` so that you don't need to download manually from Google Drive.

I think this doesn't have anything to do with gdown but simply a soft limit set by Google to avoid potential abuse of automated Google drive downloads.

I remember when the colab notebook was first released I had this problem but it was fixed after a few hours.

**Comment by chojinie** [comment]
I'm sorry to forget to close this question.
Thanks y'all @carlosedubarreto @yohanshin
