### ISSUE TITLE
Implementation of global trajectory metric

### ISSUE THREAD

**Issue by zehongs** [yohanshin/WHAM#62]
Dear authors, would you be willing to upload the implementation of RTE, ROE, and ERVE for testing the global trajectory?

**Comment by yohanshin** [comment]
I @zehongs , I am sorry for the delayed response. In the new version of the paper, we will update global metrics with more comprehensive and globally used ones including normalized root-translation error (RTE), foot sliding (FS), and jitter. Following this, we will update the `lib/eval/evaluate_emdb.py` with those new metrics.

**Comment by polidox2** [comment]
Hi,

Tried the new update, i don't see any improvement in the foot sliding nor in the jitter, was it implemented ?

Thank you!
