### ISSUE TITLE
How to generate coco_aug_dict.pth file？

### ISSUE THREAD

**Issue by HonglinChu** [yohanshin/WHAM#69]
Thanks for your work，i have some questions about  "self.aug_dict = torch.load(_C.KEYPOINTS.COCO_AUG_DICT) "   
pmask, jittering, peak, bias both with the size of [1,1,17]. 
What criteria did you follow to generate these parameters? Could you provide the related code?

**Comment by GaigeY** [comment]
Hi, Honglin,

I've met the same problem, and I mentioned that you've already closed this issue. Have you ever solved this issue?

I followed the work published in TBME by @yohanshin , and I generated the `coco_aug_dict.pth` via the following code:
``` python
jittering = torch.ones(num_joints) * 12 * 0.001
pmask = torch.ones(1, num_joints)
peak = torch.ones(num_joints) * 250 * 0.001
bias = torch.ones(num_joints) * 25 * 0.001
```
The train_stage1 then run successfully. I'm not sure it's right to configure the augment noise, cause I failed to find more certain discription of the augment setting.

If you and @yohanshin have any key insights or suggestions, please let me know.

Best wishes,

Qijun Ying

**Comment by On-JungWoan** [comment]
I've got the same questions.
Is there any progress regarding this problem?

**Comment by GaigeY** [comment]
> I've got the same questions. Is there any progress regarding this problem?

Hi Jeongwan, I solved this issue and I'm glad to share my experience. This file is used for data augment during pre-train, and I think my generated file is enough for an initial trail to retrain _WHAM stage 1_.
You can also send an email to @yohanshin to require the official version, if you want to make some contribution for the HMR field.

**Comment by On-JungWoan** [comment]
Hi Qijun, thank you for your response. I will use the file you used. Thank you!
