### ISSUE TITLE
pytorch3d access denied

### ISSUE THREAD

**Issue by carlosedubarreto** [yohanshin/WHAM#8]
While following the installation instructions, I've got this error.

![image](https://github.com/yohanshin/WHAM/assets/4061130/36a9ab00-cbe2-42ab-a50e-fab033b37e6d)

I thought, ok, I'm usgin windows, which was not made to work with, so I went to the link from the pip installation, and I got this error

![image](https://github.com/yohanshin/WHAM/assets/4061130/cd5a013a-ce98-41b9-b395-7c6daaa4914b)

In any case, I'll try toinstall the default pytorch3d, but I wanted to let you knwo abiut what happaned, maybe it can help on somethng.

**Comment by yohanshin** [comment]
Hi @carlosedubarreto , PyTorch3D is an optional library that is required for the (future) visualization. If it doesn't work on your local workstation, you can skip the installation of PyTorch3D.

**Comment by carlosedubarreto** [comment]
Oh great, thanks for the info.
