### ISSUE TITLE
the global 3D coordinates of joints

### ISSUE THREAD

**Issue by miu200521358** [yohanshin/WHAM#81]
Hello.

Thank you for publishing your wonderful research.
I am currently attempting to reflect the estimation results of WHAM in motion using a Japanese 3DCG software called MMD.
I tried using the joints obtained from run_vis.run_vis_on_demo, but they are not stable in the vertical direction and float up and down.
Since the estimated results of the gray body that is output are stable vertically, I think I might have made a mistake in the process or missed something.
Could you please tell me the appropriate way to obtain the global 3D coordinates of the joints?
I apologize for the inconvenience and thank you in advance for your confirmation.

https://github.com/yohanshin/WHAM/assets/38824651/5817bda8-d745-46c4-9b8f-71a6805adeb5

**Comment by miu200521358** [comment]
I see, that was the case. My apologies for not realizing it earlier.
I'm very grateful to receive a reply like this!

Thank you for teaching me a method that can be tested with a video where the camera is fixed.
Does this mean that if I use the camera coordinate system's position, since the camera is fixed, it can be used synonymously with the global coordinates?
Thank you also for telling me about the -calib method.
I will try both methods.

Please continue to guide me.

**Comment by miu200521358** [comment]
I specified --calib, but the position of the pelvis in the global coordinates is still unstable...

```
python demo.py --video examples/snobbism/snobbism_1900.mp4 --save_pkl  --run_smplify --visualize --calib /mnt/c/MMD/mmd-auto-trace-4/WHAM/output/calib.txt
```

Could you please teach me if there is a way to stably obtain the global coordinates of the pelvis, or a method to calculate it with assistance?
Any advice, hints, or ideas would be appreciated.
Please guide me.

![image](https://github.com/yohanshin/WHAM/assets/38824651/beaf0766-8a9e-4930-a1cf-d4e5163549c4)

**Comment by ktxu1224** [comment]
> Thank you for your reply. I apologize for my late response. This time, I have decided to refer to another study.

@miu200521358 hello, I met the same question that the global traj is drifting or floating, I wonder whether you have fixed it?

**Comment by miu200521358** [comment]
I adopted other research.

**Comment by ktxu1224** [comment]
> I adopted other research.

Can you share the method you adopted? @miu200521358

**Comment by miu200521358** [comment]
It's [4D-Humans](https://github.com/shubham-goel/4D-Humans)

**Comment by AlexMorgand** [comment]
Thanks @miu200521358 for sharing :)

**Comment by sonukiller** [comment]
@miu200521358 

Just curious about how did you re-target the SMPL model motion to your custom character... Did you use Rokoko?
And one more thing, about 4D-human, do you feel it is better than WHAM?

**Comment by miu200521358** [comment]
> Just curious about how did you re-target the SMPL model motion to your custom character... 
> Did you use Rokoko? 

No, I am not using Rokoko.
I am handling it with a custom library.
I calculate the joint angles from the vertex vectors and the original pose vectors.

> And one more thing, about 4D-human, do you feel it is better than WHAM?

Yes, the processing speed is significantly slower, so it is not suitable for real-time use, but since it is carefully estimated, I think the accuracy is high.

**Comment by sonukiller** [comment]
@miu200521358 
Thanks for the information! I have doubt regarding applying the motion to custom character... I have written a blender script which uses pose from the `wham_output.pkl` and find the rotation matrix for each joint. Though my script works for SMPLX rigged characters but fails on Mixamo characters, have you tried animating Mixamo character using your custom library?

**Comment by miu200521358** [comment]
No, I am not using Mixamo. I am using a Japanese 3DCG software called MMD.
