### ISSUE TITLE
output

### ISSUE THREAD

**Issue by carlosedubarreto** [yohanshin/WHAM#9]
I was able to install and run the evaluation code, but where is the output? I couldnt find it. I just found a yaml file on the experiments folder.

**Comment by yohanshin** [comment]
Hi @carlosedubarreto , the current evaluation code is to reproduce the values of the tables in our main paper. If you want to save the SMPL parameters, you can edit a few lines to store the results. The future demo code with custom videos will support visualization and storing SMPL parameters. Thanks!

**Comment by carlosedubarreto** [comment]
Thanks a lot @yohanshin , Better to wait then ☺

Have a great new year
