### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by ThunderVVV** [yohanshin/WHAM#93]
When I run the demo using:
`python demo.py --video examples/IMG_9732.mov --visualize`
It report that RuntimeError: CUDA error: out of memory
So what is the least cuda memory requirements?

**Comment by yohanshin** [comment]
I think it was 9GB to run 20 seconds demo... but I don't have the exact number for now. What is your GPU machine specification?

**Comment by ThunderVVV** [comment]
Ok. I used RTX 3080 before, maybe its memory is not enough. Thank you very much!
